# Generated by Django 6.0.5 on 2026-05-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=60)),
                ('Patient_ID', models.CharField(max_length=4)),
                ('Patient_Phone_No', models.IntegerField()),
                ('Patient_Treatment', models.TextField()),
                ('Patient_Doctor', models.CharField(max_length=60)),
            ],
        ),
    ]
