# Generated by Django 6.0.5 on 2026-05-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Name', models.CharField(max_length=60)),
                ('Doctor_Specialization', models.CharField(max_length=50)),
                ('No_Of_Patients', models.IntegerField()),
                ('Doctor_Contact_No', models.IntegerField()),
            ],
        ),
    ]
